cleanup and gemc3 restarting counter from 1.0

diff --git a/pinstall/install_gemc b/pinstall/install_gemc
--- a/pinstall/install_gemc
+++ b/pinstall/install_gemc
@@ -19,7 +19,13 @@ echo
 
 echo " > Checking missing modules in sim version $pv"
 module unload gemc     -s
-module load	  gemc/$gemc_version -s
+module load	  gemc/$gemc_version
+
+# if the above command fails, exit
+if [[ $? -ne 0 ]]; then
+	echo " > ERROR: gemc3/$gemc3_version is not available. Exiting."
+	exit 1
+fi
 
 [ "$(moduleTestResult .clhep     $CLHEP_VERSION )"    -eq 0 ] && echo " > clhep is installed"    || install_clhep
 [ "$(moduleTestResult .xercesc   $XERCESC_VERSION )"  -eq 0 ] && echo " > xercesc is installed"  || install_xercesc
